dist: trusty

services:
  docker

script: skip

before_deploy: 
  - make build
  - make package

deploy:
  provider: releases
  api_key: $GITHUB_API_KEY
  file_glob: true
  file: artefacts/*
  skip_cleanup: true
  on:
    tags: true